version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ResumeSAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16brtnsakwe31"
s3_prefix = "ResumeSAM"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

